version: "3.8"

services:
  user:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USER_NAME=user
        - SHELL_NAME=bash
    tty: true
    environment:
      TERM: xterm-256color
